/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zwc' at '16-8-9 下午1:47' with Gradle 2.14.1
 *
 * @author zwc, @date 16-8-9 下午1:47
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
