/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zwc' at '16-9-22 上午8:41' with Gradle 2.14.1
 *
 * @author zwc, @date 16-9-22 上午8:41
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
